/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edu.gui.Client;

import MapCircuit.launch;
import com.edu.DAO.CommentaireDAO;
import com.edu.DAO.offreDAO;
import com.edu.entities.Commentaire;
import com.edu.gui.authentification;
import java.awt.Component;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.ListModel;
import like.like;
import rating.rating;

/**
 *
 * @author MrBenrhouma
 */
public class InfoOffre extends javax.swing.JFrame {
    
    
    public static int idcom;
    /**
     * Creates new form InfoOffre
     */
    public InfoOffre() {
        initComponents();
    }
   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtsujet = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        res = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listcom = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        mssge = new javax.swing.JLabel();
        btnjaime = new javax.swing.JButton();
        nbrj = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        rat2 = new javax.swing.JLabel();
        pan = new javax.swing.JPanel();
        rat1 = new javax.swing.JLabel();
        rat3 = new javax.swing.JLabel();
        rat4 = new javax.swing.JLabel();
        rat5 = new javax.swing.JLabel();
        rat6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        d = new javax.swing.JLabel();
        e = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Programme");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtsujet.setColumns(20);
        jtsujet.setRows(5);
        jScrollPane1.setViewportView(jtsujet);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 390, 290, 80));

        jButton2.setText("Valider Commentaire");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Commenter");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));
        getContentPane().add(res, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 36, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Programme");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        listcom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                listcomMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listcomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listcomMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listcomMousePressed(evt);
            }
        });
        listcom.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listcomValueChanged(evt);
            }
        });
        listcom.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                listcomCaretPositionChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listcom);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 330, 410));

        jButton1.setText("Signaler commentaire");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Commentaire");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        mssge.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(mssge, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        btnjaime.setText("Jaime");
        btnjaime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjaimeActionPerformed(evt);
            }
        });
        getContentPane().add(btnjaime, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 70, -1));
        getContentPane().add(nbrj, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 40, 20));

        jButton3.setText("Map");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 70, -1));
        getContentPane().add(rat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 30));

        jLabel4.setText("Evaluer cette offre: ");

        a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b.png"))); // NOI18N
        a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aMouseExited(evt);
            }
        });

        b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b.png"))); // NOI18N
        b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bMouseExited(evt);
            }
        });

        c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b.png"))); // NOI18N
        c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cMouseExited(evt);
            }
        });

        d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b.png"))); // NOI18N
        d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dMouseExited(evt);
            }
        });

        e.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b.png"))); // NOI18N
        e.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panLayout = new javax.swing.GroupLayout(pan);
        pan.setLayout(panLayout);
        panLayout.setHorizontalGroup(
            panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLayout.createSequentialGroup()
                .addGroup(panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLayout.createSequentialGroup()
                        .addComponent(a)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(rat1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rat3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rat4))
                            .addGroup(panLayout.createSequentialGroup()
                                .addComponent(b)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(e)
                                .addGap(0, 19, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rat5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rat6)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        panLayout.setVerticalGroup(
            panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGroup(panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(a))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(c, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(d, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(e, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addComponent(b))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rat1)
                    .addComponent(rat3)
                    .addComponent(rat4)
                    .addComponent(rat5)
                    .addComponent(rat6))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 210, 80));

        jMenu2.setText("Acceuil");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar3.add(jMenu2);

        jMenu8.setText("Proposer offre");
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jMenuBar3.add(jMenu8);

        jMenu3.setText("Annonces");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar3.add(jMenu3);

        jMenu4.setText("Contact");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar3.add(jMenu4);

        jMenu6.setText("Destinations");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar3.add(jMenu6);

        jMenu5.setText("Mes Destination");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar3.add(jMenu5);

        jMenu1.setText("Paramètres");

        jMenuItem1.setText("Profil");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Changer Mot de passe");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem2.setText("Déconnexion");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar3.add(jMenu1);

        setJMenuBar(jMenuBar3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        CommentaireDAO cd = new CommentaireDAO();
        this.setLocationRelativeTo(null);
        this.setSize(800, 600);
        this.setResizable(false);
        acceuilclient ac = new acceuilclient();
        offreDAO od = new offreDAO();
        res.setText(od.FindOffreById(ac.idoffre));
        listcom.setModel(cd.AffichCommoffre(ac.idoffre));
        like l = new like();
        long nb = l.getlike(ac.idoffre, "offre");
        nbrj.setText(""+nb);
        
//        String c = cd.AffichCommoffre(ac.idoffre).getElementAt(listcom.getSelectedIndex());
        
        //listcom.setListData(cd.AffichCommoffre(ac.idoffre));
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       authentification a = new authentification();
       Commentaire c = new Commentaire();
       CommentaireDAO cd = new CommentaireDAO();
       acceuilclient ac = new acceuilclient();
       c.setComm(jtsujet.getText());
       c.setE_mail(a.identifiant);
       c.setId_offre(ac.idoffre);
       cd.insertcomoffre(c);
       listcom.setModel(cd.AffichCommoffre(ac.idoffre));
       jtsujet.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (listcom.isSelectionEmpty()) {
            mssge.setText("Veuillez sélectioner un commentaire");
        }
        else
        {
        Signalercomm scg = new Signalercomm();
        scg.setVisible(true);
        this.setVisible(false);
        }
      
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        acceuilclient ac = new acceuilclient();
        ac.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
        ProposerDestinationClient po = new ProposerDestinationClient();
        po.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu8MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        ConsulterAnnonces ca = new ConsulterAnnonces();
        ca.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        MailJframe mj = new MailJframe();
        mj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        Destinations d = new Destinations();
        d.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        MesDestinations md = new MesDestinations();
        md.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Profil p = new Profil();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        EditPassowrd ep = new EditPassowrd();
        ep.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        authentification a = new authentification();
        a.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void listcomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listcomMouseClicked
    
    }//GEN-LAST:event_listcomMouseClicked

    private void listcomMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listcomMouseReleased
    
    }//GEN-LAST:event_listcomMouseReleased

    private void listcomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listcomMouseEntered
  
    }//GEN-LAST:event_listcomMouseEntered

    private void listcomValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listcomValueChanged
    
    }//GEN-LAST:event_listcomValueChanged

    private void listcomCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_listcomCaretPositionChanged

    }//GEN-LAST:event_listcomCaretPositionChanged

    private void listcomMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listcomMousePressed
        CommentaireDAO cd = new CommentaireDAO();
        authentification a = new authentification();
        acceuilclient can = new acceuilclient();
        int c = listcom.getSelectedIndex();
        List <String> l = new ArrayList<String>();
        l=cd.DisplayIdcommOffre(can.idoffre);
        String ma = l.get(c);
        idcom = Integer.parseInt(ma);
        //String ch = (String) listcom.getSelectedValue();
        //int pos= ch.indexOf(" ");
        //String st="";
        //for (int j = 0; j < pos; j++) {
        //   st = st + ch.charAt(j);
       // }
        //idcom =Integer.parseInt(st);
        if(cd.AffichCommmail(idcom).equals(a.identifiant)){
            jButton1.setEnabled(false);
            
                
            }
        else
        {
            jButton1.setEnabled(true);
            
        }

    }//GEN-LAST:event_listcomMousePressed

    private void btnjaimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjaimeActionPerformed
        like l = new like();
        
        l.addlike(acceuilclient.idoffre,"offre");
         long n = l.getlike(acceuilclient.idoffre,"offre"); 
        nbrj.setText(""+n);
        btnjaime.setEnabled(false);
    }//GEN-LAST:event_btnjaimeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String ch = acceuilclient.circuit;
        String[] args = null;
        System.out.println(ch);
         String c[] = ch.split(",");
        System.out.println("pays:"+c[0]+" "+c[1]);
        launch.setA(c[0]);
        launch.setB(c[1]);
        launch.main(args);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void aMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseEntered
        try {
            BufferedImage imgtwo=null;
            imgtwo = ImageIO.read(new File("res/b.png"));
            final ImageIcon imageIcontwo = new ImageIcon(imgtwo);
            BufferedImage imgOne=null;
            imgOne = ImageIO.read(new File("res/a.png"));
            final ImageIcon imageIconOne = new ImageIcon(imgOne);
            a.setIcon(imageIconOne);
            b.setIcon(imageIcontwo);
            c.setIcon(imageIcontwo);
            d.setIcon(imageIcontwo);
            e.setIcon(imageIcontwo);
        } catch (IOException ex) {
            Logger.getLogger(InfoOffre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_aMouseEntered

    private void aMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseExited
       try {
            BufferedImage imgtwo=null;
            imgtwo = ImageIO.read(new File("res/b.png"));
            final ImageIcon imageIcontwo = new ImageIcon(imgtwo);
            BufferedImage imgOne=null;
            imgOne = ImageIO.read(new File("res/a.png"));
            final ImageIcon imageIconOne = new ImageIcon(imgOne);
            a.setIcon(imageIcontwo);
            
        } catch (IOException ex) {
            Logger.getLogger(InfoOffre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_aMouseExited

    private void bMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMouseEntered
         try {
             BufferedImage imgtwo=null;
            imgtwo = ImageIO.read(new File("res/b.png"));
            final ImageIcon imageIcontwo = new ImageIcon(imgtwo);
            BufferedImage imgOne=null;
            imgOne = ImageIO.read(new File("res/a.png"));
            final ImageIcon imageIconOne = new ImageIcon(imgOne);
            a.setIcon(imageIconOne);
            b.setIcon(imageIconOne);
             c.setIcon(imageIcontwo);
            d.setIcon(imageIcontwo);
            e.setIcon(imageIcontwo);
        } catch (IOException ex) {
            Logger.getLogger(InfoOffre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bMouseEntered

    private void cMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMouseEntered
         try {
             BufferedImage imgtwo=null;
            imgtwo = ImageIO.read(new File("res/b.png"));
            final ImageIcon imageIcontwo = new ImageIcon(imgtwo);
            BufferedImage imgOne=null;
            imgOne = ImageIO.read(new File("res/a.png"));
            final ImageIcon imageIconOne = new ImageIcon(imgOne);
            a.setIcon(imageIconOne);
            b.setIcon(imageIconOne);
            c.setIcon(imageIconOne);
            d.setIcon(imageIcontwo);
            e.setIcon(imageIcontwo);
        } catch (IOException ex) {
            Logger.getLogger(InfoOffre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cMouseEntered

    private void dMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dMouseEntered
         try {
             BufferedImage imgtwo=null;
            imgtwo = ImageIO.read(new File("res/b.png"));
            final ImageIcon imageIcontwo = new ImageIcon(imgtwo);
            BufferedImage imgOne=null;
            imgOne = ImageIO.read(new File("res/a.png"));
            final ImageIcon imageIconOne = new ImageIcon(imgOne);
            a.setIcon(imageIconOne);
            b.setIcon(imageIconOne);
            c.setIcon(imageIconOne);
            d.setIcon(imageIconOne);
            e.setIcon(imageIcontwo);
        } catch (IOException ex) {
            Logger.getLogger(InfoOffre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dMouseEntered

    private void eMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eMouseEntered
         try {
            BufferedImage imgtwo=null;
            imgtwo = ImageIO.read(new File("res/b.png"));
            final ImageIcon imageIcontwo = new ImageIcon(imgtwo); 
            BufferedImage imgOne=null;
            imgOne = ImageIO.read(new File("res/a.png"));
            final ImageIcon imageIconOne = new ImageIcon(imgOne);
            a.setIcon(imageIconOne);
            b.setIcon(imageIconOne);
            c.setIcon(imageIconOne);
            d.setIcon(imageIconOne);
            e.setIcon(imageIconOne);
        } catch (IOException ex) {
            Logger.getLogger(InfoOffre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_eMouseEntered

    private void bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMouseExited
      
    }//GEN-LAST:event_bMouseExited

    private void cMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMouseExited
     
    }//GEN-LAST:event_cMouseExited

    private void dMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dMouseExited
      
    }//GEN-LAST:event_dMouseExited

    private void eMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eMouseExited
       
    }//GEN-LAST:event_eMouseExited

    private void eMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eMouseClicked
       int tot=1;
       System.out.println("of");
       rating r = new rating();
       r.addRating(acceuilclient.idoffre,tot,"offre");
    }//GEN-LAST:event_eMouseClicked

    private void dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dMouseClicked
        int tot=1;
       System.out.println("of");
       rating r = new rating();
       r.addRating(acceuilclient.idoffre,tot,"offre");
    }//GEN-LAST:event_dMouseClicked

    private void cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMouseClicked
         int tot=1;
       System.out.println("of");
       rating r = new rating();
       r.addRating(acceuilclient.idoffre,tot,"offre");
    }//GEN-LAST:event_cMouseClicked

    private void bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMouseClicked
        int tot=1;
       System.out.println("of");
       rating r = new rating();
       r.addRating(acceuilclient.idoffre,tot,"offre");
    }//GEN-LAST:event_bMouseClicked

    private void aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseClicked
       int tot=1;
       System.out.println("of");
       rating r = new rating();
       r.addRating(acceuilclient.idoffre,tot,"offre");
    }//GEN-LAST:event_aMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws MalformedURLException, IOException {
         BufferedImage imgOne=null;
         BufferedImage imgTwo=null;
         final JButton t;
         
        System.out.println(System.getProperty("user.dir"));
        try {
            //new File(System.getProperty("user.dir")+"src/images/ratgris.png")
            //System.getProperty("user_dir")+File.separator+"image"+File.separator+"im0001.jpg";
            //this.getClass().getResource("/images/pic1.jpg")
            //new File(getClass().getResource("/resources/image.jpg").toURI())
            //URL im = InfoOffre.class.getResource("/Voyage_a_la_carte1.9/src/Images"+File.separator+"ratgris.png");
            imgOne = ImageIO.read(new File("res/a.png"));
            imgTwo = ImageIO.read(new File("res/b.png"));
            final ImageIcon imageIconOne = new ImageIcon(imgOne);
            final ImageIcon imageIconTwo = new ImageIcon(imgTwo);
            t = new JButton(imageIconOne);
            t.addMouseListener(new MouseListener() {            
            @Override
            public void mouseReleased(MouseEvent arg0) {}           
            @Override
            public void mousePressed(MouseEvent arg0) {}            
            @Override
            public void mouseExited(MouseEvent arg0) { 
                t.setIcon(imageIconOne);
            }           
            @Override
            public void mouseEntered(MouseEvent arg0) {
                    t.setIcon(imageIconTwo);
            }           
            @Override
            public void mouseClicked(MouseEvent arg0) {}

        });
            
            } catch (IOException ex) {
            Logger.getLogger(InfoOffre.class.getName()).log(Level.SEVERE, null, ex);
        }
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(InfoOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(InfoOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(InfoOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(InfoOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new InfoOffre().setVisible(true);
                }
            });
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JLabel b;
    private javax.swing.JButton btnjaime;
    private javax.swing.JLabel c;
    private javax.swing.JLabel d;
    private javax.swing.JLabel e;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jtsujet;
    private javax.swing.JList listcom;
    private javax.swing.JLabel mssge;
    private javax.swing.JLabel nbrj;
    private javax.swing.JPanel pan;
    private javax.swing.JLabel rat1;
    private javax.swing.JLabel rat2;
    private javax.swing.JLabel rat3;
    private javax.swing.JLabel rat4;
    private javax.swing.JLabel rat5;
    private javax.swing.JLabel rat6;
    private javax.swing.JLabel res;
    // End of variables declaration//GEN-END:variables
}
