/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edu.gui.Client;

import com.edu.DAO.ClientDAO;
import com.edu.entities.Client;
import com.edu.gui.Client.ProposerDestinationClient;
import com.edu.gui.authentification;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;


/**
 *
 * @author MrBenrhouma
 */
public class Profil extends javax.swing.JFrame {
    public static String filename;
    public static FileInputStream fistream;
    /**
     * Creates new form Profil
     */
    public Profil() {
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profil = new javax.swing.JLabel();
        tfcin = new javax.swing.JTextField();
        tfnom = new javax.swing.JTextField();
        tfprenom = new javax.swing.JTextField();
        tfville = new javax.swing.JTextField();
        tfmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlmail = new javax.swing.JLabel();
        jlCIN = new javax.swing.JLabel();
        jlnom = new javax.swing.JLabel();
        jlprenom = new javax.swing.JLabel();
        jlville = new javax.swing.JLabel();
        modcin = new javax.swing.JLabel();
        modnom = new javax.swing.JLabel();
        modpren = new javax.swing.JLabel();
        modville = new javax.swing.JLabel();
        modmail7 = new javax.swing.JLabel();
        jlclient = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnvalider1 = new javax.swing.JLabel();
        x1 = new javax.swing.JLabel();
        x = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Arriére = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Profil");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profil.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        profil.setForeground(new java.awt.Color(255, 90, 0));
        profil.setText("Information");
        getContentPane().add(profil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        tfcin.setBackground(new java.awt.Color(76, 75, 75));
        tfcin.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tfcin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 170, -1));

        tfnom.setBackground(new java.awt.Color(76, 75, 75));
        tfnom.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tfnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 170, -1));

        tfprenom.setBackground(new java.awt.Color(76, 75, 75));
        tfprenom.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tfprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 170, -1));

        tfville.setBackground(new java.awt.Color(76, 75, 75));
        tfville.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tfville, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 170, -1));

        tfmail.setBackground(new java.awt.Color(76, 75, 75));
        tfmail.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tfmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 170, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 90, 0));
        jLabel2.setText("Nom");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 90, 0));
        jLabel3.setText("Prénom");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 90, 0));
        jLabel4.setText("CIN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 90, 0));
        jLabel5.setText("Ville");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 90, 0));
        jLabel7.setText("E_mail");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jlmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlmail.setForeground(new java.awt.Color(255, 255, 255));
        jlmail.setText("jLabel1");
        getContentPane().add(jlmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jlCIN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlCIN.setForeground(new java.awt.Color(255, 255, 255));
        jlCIN.setText("jLabel6");
        getContentPane().add(jlCIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        jlnom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlnom.setForeground(new java.awt.Color(255, 255, 255));
        jlnom.setText("jLabel8");
        getContentPane().add(jlnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        jlprenom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlprenom.setForeground(new java.awt.Color(255, 255, 255));
        jlprenom.setText("jLabel9");
        getContentPane().add(jlprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));

        jlville.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlville.setForeground(new java.awt.Color(255, 255, 255));
        jlville.setText("jLabel10");
        getContentPane().add(jlville, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        modcin.setForeground(new java.awt.Color(0, 153, 255));
        modcin.setText("Modifier");
        modcin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modcinMouseClicked(evt);
            }
        });
        getContentPane().add(modcin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        modnom.setForeground(new java.awt.Color(0, 153, 255));
        modnom.setText("Modifier");
        modnom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modnomMouseClicked(evt);
            }
        });
        getContentPane().add(modnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        modpren.setForeground(new java.awt.Color(0, 153, 255));
        modpren.setText("Modifier");
        modpren.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modprenMouseClicked(evt);
            }
        });
        getContentPane().add(modpren, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, -1));

        modville.setForeground(new java.awt.Color(0, 153, 255));
        modville.setText("Modifier");
        modville.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modvilleMouseClicked(evt);
            }
        });
        getContentPane().add(modville, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, -1));

        modmail7.setForeground(new java.awt.Color(0, 153, 255));
        modmail7.setText("Modifier");
        modmail7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modmail7MouseClicked(evt);
            }
        });
        getContentPane().add(modmail7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        jlclient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlclient.setForeground(new java.awt.Color(0, 204, 0));
        jlclient.setText("jLabel1");
        getContentPane().add(jlclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, 40));

        message.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        message.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 590, 250, 20));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, -1));

        pic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 90, 0), 2));
        getContentPane().add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 100, 100));

        jButton1.setForeground(new java.awt.Color(0, 153, 255));
        jButton1.setText("Photo de profil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, -1, -1));

        btnvalider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnvalider1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnvalider1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnvalider1MouseExited(evt);
            }
        });
        getContentPane().add(btnvalider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 630, 123, 35));

        x1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                x1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                x1MouseExited(evt);
            }
        });
        getContentPane().add(x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 30, 30));

        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xMouseExited(evt);
            }
        });
        getContentPane().add(x, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 30, 30));

        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 50));

        Arriére.setForeground(new java.awt.Color(255, 90, 0));
        getContentPane().add(Arriére, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        pic.setSize(100, 100); 
        this.setLocationRelativeTo(null);
         this.setSize(580, 700);
         this.setResizable(false);
         BufferedImage imgHome = null;
        try {
            imgHome = ImageIO.read(new File("res/arriere.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(Profil.class.getName()).log(Level.SEVERE, null, ex);
        }
          Image ri = imgHome.getScaledInstance(Arriére.getWidth(), Arriére.getHeight(), 0);
          Arriére.setIcon(new ImageIcon(ri));
         
         authentification a = new authentification();
         ClientDAO cd = new ClientDAO();
         Client c = new Client();
         c=cd.chercherClient(a.identifiant);
         jlmail.setText(c.getEmail());
         
         jlnom.setText(c.getNom());
         jlprenom.setText(c.getPrenom());
         jlville.setText(c.getVille());
         
         tfcin.setVisible(false);
         tfmail.setVisible(false);
         tfnom.setVisible(false);
         tfprenom.setVisible(false);
         tfville.setVisible(false);
         
         tfmail.setText(c.getEmail());
        
         tfnom.setText(c.getNom());
         tfprenom.setText(c.getPrenom());
         tfville.setText(c.getVille());
         c=cd.chercherClient(a.identifiant);
         tfnom.setText(c.getNom());
         ImageIcon ima = new ImageIcon();
         ima = cd.chercherImageClient(a.identifiant);
         pic.setIcon(ima);
        
         jlclient.setText(c.getNom()+" "+c.getPrenom());
         
        BufferedImage imgv = null;
        try {
            imgv = ImageIO.read(new File("res/valider off.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(InfoAnnonce.class.getName()).log(Level.SEVERE, null, ex);
        }
          Image ridv = imgv.getScaledInstance(btnvalider1.getWidth(), btnvalider1.getHeight(), 0);
          btnvalider1.setIcon(new ImageIcon(ridv));
          
            BufferedImage imgx = null;
        try {
            imgx = ImageIO.read(new File("res/x1.png"));
        } catch (IOException ex) {
            Logger.getLogger(EditPassowrd.class.getName()).log(Level.SEVERE, null, ex);
        }
          Image ridx = imgx.getScaledInstance(x.getWidth(), x.getHeight(), 0);
          x.setIcon(new ImageIcon(ridx));
          
          BufferedImage imgxr = null;
        try {
            imgxr = ImageIO.read(new File("res/-1.png"));
        } catch (IOException ex) {
            Logger.getLogger(EditPassowrd.class.getName()).log(Level.SEVERE, null, ex);
        }
          Image ridxr = imgxr.getScaledInstance(x1.getWidth(), x1.getHeight(), 0);
          x1.setIcon(new ImageIcon(ridxr));
          
              BufferedImage img = null;
        try {
            img = ImageIO.read(new File("res/accueil-off.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(Destinations.class.getName()).log(Level.SEVERE, null, ex);
        }
          Image resizedImage = img.getScaledInstance(Home.getWidth(), Home.getHeight(), 0);
          Home.setIcon(new ImageIcon(resizedImage));
        
    }//GEN-LAST:event_formWindowOpened

    private void modcinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modcinMouseClicked
        tfcin.setVisible(true);
    }//GEN-LAST:event_modcinMouseClicked

    private void modnomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modnomMouseClicked
        tfnom.setVisible(true);
    }//GEN-LAST:event_modnomMouseClicked

    private void modprenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modprenMouseClicked
        tfprenom.setVisible(true);
    }//GEN-LAST:event_modprenMouseClicked

    private void modvilleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modvilleMouseClicked
        tfville.setVisible(true);
    }//GEN-LAST:event_modvilleMouseClicked

    private void modmail7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modmail7MouseClicked
        tfmail.setVisible(true);
    }//GEN-LAST:event_modmail7MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            JFileChooser picchooser = new JFileChooser();
            int returnval = picchooser.showOpenDialog(null);
            File file = null;
            if(returnval == JFileChooser.APPROVE_OPTION){
                file = picchooser.getSelectedFile();
                filename = file.getAbsolutePath();
                File pics = new File(filename);
                ImageIcon ima = new ImageIcon(filename);
                fistream = new FileInputStream (pics);
                pic.setSize(100, 100);
                Image img = ImageIO.read(file);
                Image resizedImage = img.getScaledInstance(pic.getWidth(), pic.getHeight(), 0);
               pic.setIcon(new ImageIcon(resizedImage));
                //pic.setIcon(ima);

            }
        } catch(Exception e){
            e.printStackTrace();
        }
                                            

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnvalider1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvalider1MouseClicked
         authentification a = new authentification();
        ClientDAO cd = new ClientDAO();
        InputStream img = getClass().getClassLoader().getResourceAsStream(filename);
        cd.updateClient(a.identifiant, tfcin.getText(), tfnom.getText(), tfprenom.getText(), tfville.getText(),fistream);
        message.setText("Modification terminé avec succée");
    }//GEN-LAST:event_btnvalider1MouseClicked

    private void btnvalider1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvalider1MouseEntered
        BufferedImage imgv = null;
        try {
            imgv = ImageIO.read(new File("res/valider on.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(InfoAnnonce.class.getName()).log(Level.SEVERE, null, ex);
        }
        Image ridv = imgv.getScaledInstance(btnvalider1.getWidth(), btnvalider1.getHeight(), 0);
        btnvalider1.setIcon(new ImageIcon(ridv));
    }//GEN-LAST:event_btnvalider1MouseEntered

    private void btnvalider1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvalider1MouseExited
        BufferedImage imgv = null;
        try {
            imgv = ImageIO.read(new File("res/valider off.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(InfoAnnonce.class.getName()).log(Level.SEVERE, null, ex);
        }
        Image ridv = imgv.getScaledInstance(btnvalider1.getWidth(), btnvalider1.getHeight(), 0);
        btnvalider1.setIcon(new ImageIcon(ridv));
    }//GEN-LAST:event_btnvalider1MouseExited

    private void x1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x1MouseClicked

    }//GEN-LAST:event_x1MouseClicked

    private void x1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x1MouseEntered
        BufferedImage imgxr = null;
        try {
            imgxr = ImageIO.read(new File("res/-2.png"));
        } catch (IOException ex) {
            Logger.getLogger(acceuilclient.class.getName()).log(Level.SEVERE, null, ex);
        }
        Image ridxr = imgxr.getScaledInstance(x1.getWidth(), x1.getHeight(), 0);
        x1.setIcon(new ImageIcon(ridxr));
    }//GEN-LAST:event_x1MouseEntered

    private void x1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x1MouseExited
        BufferedImage imgxr = null;
        try {
            imgxr = ImageIO.read(new File("res/-1.png"));
        } catch (IOException ex) {
            Logger.getLogger(acceuilclient.class.getName()).log(Level.SEVERE, null, ex);
        }
        Image ridxr = imgxr.getScaledInstance(x1.getWidth(), x1.getHeight(), 0);
        x1.setIcon(new ImageIcon(ridxr));
    }//GEN-LAST:event_x1MouseExited

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        System.exit(0);
    }//GEN-LAST:event_xMouseClicked

    private void xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseEntered
        BufferedImage imgx = null;
        try {
            imgx = ImageIO.read(new File("res/x2.png"));
        } catch (IOException ex) {
            Logger.getLogger(acceuilclient.class.getName()).log(Level.SEVERE, null, ex);
        }
        Image ridx = imgx.getScaledInstance(x.getWidth(), x.getHeight(), 0);
        x.setIcon(new ImageIcon(ridx));
    }//GEN-LAST:event_xMouseEntered

    private void xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseExited
        BufferedImage imgx = null;
        try {
            imgx = ImageIO.read(new File("res/x1.png"));
        } catch (IOException ex) {
            Logger.getLogger(acceuilclient.class.getName()).log(Level.SEVERE, null, ex);
        }
        Image ridx = imgx.getScaledInstance(x.getWidth(), x.getHeight(), 0);
        x.setIcon(new ImageIcon(ridx));
    }//GEN-LAST:event_xMouseExited

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        acceuilclient ac = new acceuilclient();
        ac.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeMouseClicked

    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        BufferedImage img2 = null;
        try {
            img2 = ImageIO.read(new File("res/accueil-on.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(acceuilclient.class.getName()).log(Level.SEVERE, null, ex);
        }
        Image resizedImage = img2.getScaledInstance(Home.getWidth(), Home.getHeight(), 0);
        Home.setIcon(new ImageIcon(resizedImage));
    }//GEN-LAST:event_HomeMouseEntered

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        BufferedImage img2 = null;
        try {
            img2 = ImageIO.read(new File("res/accueil-off.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(acceuilclient.class.getName()).log(Level.SEVERE, null, ex);
        }
        Image resizedImage = img2.getScaledInstance(Home.getWidth(), Home.getHeight(), 0);
        Home.setIcon(new ImageIcon(resizedImage));
    }//GEN-LAST:event_HomeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profil().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Arriére;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel btnvalider1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jlCIN;
    private javax.swing.JLabel jlclient;
    private javax.swing.JLabel jlmail;
    private javax.swing.JLabel jlnom;
    private javax.swing.JLabel jlprenom;
    private javax.swing.JLabel jlville;
    private javax.swing.JLabel message;
    private javax.swing.JLabel modcin;
    private javax.swing.JLabel modmail7;
    private javax.swing.JLabel modnom;
    private javax.swing.JLabel modpren;
    private javax.swing.JLabel modville;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel profil;
    private javax.swing.JTextField tfcin;
    private javax.swing.JTextField tfmail;
    private javax.swing.JTextField tfnom;
    private javax.swing.JTextField tfprenom;
    private javax.swing.JTextField tfville;
    private javax.swing.JLabel x;
    private javax.swing.JLabel x1;
    // End of variables declaration//GEN-END:variables

    
    }

